remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: <h1 align="center" style="color:#B48D77; font-family:"Lao MN"; font-size:150%;">L&ensp;&emsp;U&ensp;&emsp;N&ensp;&emsp;A</h1>
logo: assets/luna.png
description: <p align = "center">Complete your tasks by night.<p align = "center">
